# Generated by Django 4.0.4 on 2022-05-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('expired', 'EXPIRED'), ('failed', 'FAILED'), ('canceled', 'CANCELED'), ('paid', 'PAID'), ('progress', 'IN PROGRESS')], default='progress', max_length=25),
        ),
    ]
